### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Sparkenstein** [Sparkenstein/txt#1]
- [ ] move to mithril SSR
- [ ] merge server and client to server
- [ ] symmetric key encryption
  - [ ] password protection
- [ ] login signup system
- [ ] toggle themes
- [ ] forks
